# Generated by Django 2.2.7 on 2019-11-24 21:11

from django.db import migrations
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from usuarios.models import Usuario
from transacciones.models import Transaccion
from itertools import chain

def crear_grupos(apps, schema_editor):

  user_admin = Usuario.objects.create_user('rubik@rubik.com', 'secret')
  usuarios = Group.objects.create(name='usuarios')
  permisos_transacciones = Permission.objects.filter(name__contains='transaccion')
  usuarios.permissions.set(permisos_transacciones)

  admins = Group.objects.create(name='admins')
  permisos_usuarios = Permission.objects.filter(name__contains='usuario')
  admins.permissions.set(list(chain(permisos_usuarios, permisos_transacciones)))

  user_admin.groups.set([usuarios, admins])

def eliminar_grupos(apps, schema_editor):

  Group.objects.filter(name = 'usuarios').delete()
  Group.objects.filter(name = 'admins').delete()

class Migration(migrations.Migration):

  dependencies = [
    ('usuarios', '0001_initial')
  ]

  operations = [
    migrations.RunPython(crear_grupos, eliminar_grupos)
  ]
