# Generated by Django 2.2.7 on 2019-11-28 23:37

from django.db import migrations

from transacciones.models import Transaccion
from usuarios.models import Usuario
from faker import Faker

def cargarTransacciones(apps, schema_editor):

  fake = Faker()

  for i in range(1, 10):

    usuario = Usuario.get_random()
    usuario.transaccion_set.add(Transaccion.objects.create(
      descripcion = fake.text(max_nb_chars=20),
      monto = fake.pyfloat(right_digits=2, positive=True, min_value=10, max_value=1000)
    ))

def descargarTransacciones(apps, schema_editor):

  pass

class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_transaccion_user'),
    ]

    operations = [
      migrations.RunPython(cargarTransacciones, descargarTransacciones)
    ]
