# Generated by Django 3.0.3 on 2020-02-25 02:14

from django.db import migrations
from faker import Faker
from usuarios.models import Usuario
from user_accounts.models import UserAccount

def seed_user_accounts(apps, schema_editor):

  fake = Faker()

  for i in range(1, 3):

    user = Usuario.get_random()
    if(fake.pybool()):

      user.accounts.create(
        name= fake.text(max_nb_chars=20),
        amount=fake.pyfloat(right_digits=2, positive=True, min_value=300, max_value=1200)
      )

def unseed_user_accounts(apps, schema_editor):
  pass

class Migration(migrations.Migration):

  dependencies = [
    ('user_accounts', '0001_initial'),
    ('usuarios', '0002_auto_20200225_2143')
  ]

  operations = [
    migrations.RunPython(seed_user_accounts, unseed_user_accounts)
  ]
